### ISSUE TITLE
October 2021 Update

### ISSUE THREAD

**Issue by codingbandit** [microsoft/MCW-Leveraging-Azure-Digital-Twins-in-a-supply-chain#3]
Note: Azure Digital Twins Explorer is still in public preview (when is the release date for this)
- update screenshots and instructions for new UI flows
- add energy grid ontology to ontologies list
- expand  Azure Digital Twins query language guidance (show more examples)
- add SDK example? re: https://techcommunity.microsoft.com/t5/internet-of-things/how-to-speed-up-azure-digital-twins-queries-with-caching/ba-p/2551153

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #5
